services:
  app:
    image: php:8.2-cli
    ports:
      - 127.0.0.1:8080:80
    working_dir: /app
    volumes:
      - .:/app

  tests:
    image: php:8.2-cli
    volumes:
      - .:/app
    working_dir: /app/
    entrypoint: vendor/bin/phpunit

volumes:
  cartmanager-mysql-data: